language: node_js
node_js:
  - "9"
cache: 
  - pip
  - npm
before_install:
  - pyenv local 3.7.1
install:
  - pip install --upgrade pip
  - pip install codecov
script:
  - cd utilities
  - echo ${TRAVIS_BRANCH}
  - python install.py branch ${TRAVIS_BRANCH}
  - cd ..
  # - python -m pytest --cov=nwb_explorer
  - coverage run --source pygeppetto -m pytest -v 
  - coverage report -m
after_success:
  - codecov