language: node_js
node_js:
  - "9"
cache: 
  - pip
  - npm
before_install:
  - pyenv local 3.7.1
before_script:
  - pip install --upgrade pip
script:
  - cd utilities
  - python install.py branch pynwb